### ISSUE TITLE
[Question] In Configuration>Local_Interfaces, should I put a check mark by Wan and Wan6 (or just Lan)?

### ISSUE THREAD

**Issue by hub2git** [jow-/nlbwmon#6]
In "Netlink Bandwidth Monitor - Configuration"/"Local interfaces", which should be selected?

Lan [the only one selected by default]
Wan
Wan6

![lede_nlbwmon_configuration_local_interfaces](https://user-images.githubusercontent.com/7141051/29399750-4d72b896-82df-11e7-9975-637d91d06eda.png)

![luci network interfaces thu aug 17 00 01 15 pdt 2017](https://user-images.githubusercontent.com/7141051/29399756-55c7f416-82df-11e7-87b8-5a7d62554e06.png)

If there's any other info that would help you help me, please let me know.

**Comment by jow-** [comment]
You should only select internal ifaces.

**Comment by johnlane** [comment]
@jow would you please explan the reason for this?
 
I've recently installed `nlbwmon` and I was also unsure how I should configure this setting. In my case I have `lan`, `dmz`, `vpn`, `wan` and `wan6`. Since reading this I only have `lan` and `dmz` selected. I was wondering whether I should also select my `vpn` (because it's part of the internal network) ?
